spring.application.name=AILogistics-FrontEnd

server.port=2222

logging.level.org.springframework.security=DEBUG

# Groq API configuration (OpenAI-compatible)
#Create your key from following URL
#https://console.groq.com/keys
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.api-key=Your-Key
spring.ai.openai.chat.options.model=openai/gpt-oss-120b


# ===============================
# Security - Google OAuth2

#Google Oauth2 link to create secret id:
#https://console.cloud.google.com/apis

#Authorized redirect URIs
#http://localhost:2222/login/oauth2/code/google
# ===============================
spring.security.oauth2.client.registration.google.client-id=your-id
spring.security.oauth2.client.registration.google.client-secret=your-secret-code
spring.security.oauth2.client.registration.google.scope=profile,email


#The maximum size allowed for a single uploaded file.
spring.servlet.multipart.max-file-size=1000MB  
#The total size of the entire request (all form data + all files combined).
spring.servlet.multipart.max-request-size=10000MB

# ===============================
# Custom Values
# ===============================
rest_webservice_url=http://localhost:5555

